debug: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webflash?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
server:
  tomcat:
    basedir: tmp

